"""Conjecture validators package."""

from .common import ValidationResult, VerificationError
from .validators_11 import (
    VALIDATORS as VALIDATORS_11,
    verify_pratt_certificate,
    verify_firoozbakht,
    verify_second_hardy_littlewood,
    verify_euler_sum_of_powers,
    verify_bpsw_standard,
    verify_weak_selfridge_fibonacci,
    verify_grantham_challenge,
    verify_bfw_enhanced,
    verify_wall_sun_sun,
    verify_complex_jacobian,
    verify_prp,
    verify_rigid_finite_projective_plane,
)
from .validators_20 import (
    VALIDATORS as VALIDATORS_20,
    verify_turyn_type_tt46,
    verify_skew_hadamard_356,
    verify_cocyclic_hadamard_188,
    verify_finite_magma_e677_not_e255,
    verify_line_graph_inertia,
    verify_dual_finite_magma,
    verify_max_laplacian_eigenvalue,
    verify_max_laplacian_11,
    verify_max_laplacian_40,
    verify_max_laplacian_44,
    verify_max_laplacian_46,
    verify_max_laplacian_56,
    verify_distance_spectral_independence_inertia,
    verify_erdos_97,
    verify_erdos_811,
    verify_symmetric_conference_matrix_86,
    verify_rshcd_196_type_minus,
    verify_steiner_3_design,
    verify_steiner_3_5_41,
    verify_steiner_3_6_46,
    verify_seymour_second_neighborhood,
)

VALIDATORS = {
    **VALIDATORS_11,
    **VALIDATORS_20,
}

__all__ = [
    "ValidationResult",
    "VerificationError",
    "VALIDATORS",
    "VALIDATORS_11",
    "VALIDATORS_20",
    "verify_pratt_certificate",
    "verify_firoozbakht",
    "verify_second_hardy_littlewood",
    "verify_euler_sum_of_powers",
    "verify_bpsw_standard",
    "verify_weak_selfridge_fibonacci",
    "verify_grantham_challenge",
    "verify_bfw_enhanced",
    "verify_wall_sun_sun",
    "verify_complex_jacobian",
    "verify_prp",
    "verify_rigid_finite_projective_plane",
    "verify_turyn_type_tt46",
    "verify_skew_hadamard_356",
    "verify_cocyclic_hadamard_188",
    "verify_finite_magma_e677_not_e255",
    "verify_line_graph_inertia",
    "verify_dual_finite_magma",
    "verify_max_laplacian_eigenvalue",
    "verify_max_laplacian_11",
    "verify_max_laplacian_40",
    "verify_max_laplacian_44",
    "verify_max_laplacian_46",
    "verify_max_laplacian_56",
    "verify_distance_spectral_independence_inertia",
    "verify_erdos_97",
    "verify_erdos_811",
    "verify_symmetric_conference_matrix_86",
    "verify_rshcd_196_type_minus",
    "verify_steiner_3_design",
    "verify_steiner_3_5_41",
    "verify_steiner_3_6_46",
    "verify_seymour_second_neighborhood",
]
